version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB:  $DATABASE_USERNAME
    ports:
      - 5432:5432
      
volumes:
  db: