version: '3.8'

services:
  back:
    image: ghcr.io/chakra-ui-admin/chakra-ui-admin-back:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == vps15514
    networks:
      - default                
    environment:
      DATABASE_URL: postgresql://$DATABASE_USERNAME:$DATABASE_PASSWORD@db:5432/$DATABASE_USERNAME?schema=public
      APP_SECRET: $APP_SECRET      
    labels:
      - traefik.enable=true
      - traefik.http.routers.chakra-ui-admin-back.rule=Host("$DOMAIN")
      - traefik.http.routers.chakra-ui-admin-back.entrypoints=websecure
      - traefik.http.routers.chakra-ui-admin-back.tls.certresolver=letsencrypt
      - traefik.http.services.chakra-ui-admin-back.loadbalancer.server.port=4000

networks:
  default:
    external: true
    name: $OPS_NAME