version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == vps15514
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB:  $DATABASE_USERNAME
    ports:
      - 5432:5432
      
volumes:
  db: