name: CI/DI

env:
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  before:
    runs-on: vps15514
    steps:
      - uses: actions/checkout@v2

      - name: deplloy DB
        run: docker stack deploy -c ./services/pg.yml ${{ secrets.OPS_NAME }}
